<package format="3">
  <name>onrobot_2fg7_gripper_description</name>
  <version>0.0.1</version>
  <description>Description OnRobot 2FG7</description>
  <maintainer email="aarnal@robotnik.es">Alejandro Arnal</maintainer>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <license>BSD</license>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
